#pragma once
enum class FIELD_TYPE{ NUMERIC = 1, TEXT = 2 };
enum class BLOCK_TYPE { STANDART, ADMINISTRATIONS, PLOT, PLOT_PA };


enum AdminWays { 
	IV_DROPS = 1,
	INFUSION, 
	IV_BOLUS, 
	INTRAMUSCULAR, 
	SUBCUTANEOUS,
	ENTERNAL, 
	RECTAL, 
	SPINAL,  
	EPIDURAL,
	EPIDURAL_INFUSION,
	EXTERNAL,
	INHALATION,
	NASAL,
	EYE_DROPS,
	EAR_DROPS
};