//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется ArmChart.rc
//
#define IDCANCEL2                       4
#define IDR_MAINFRAME                   128
#define IDR_ARMOPETYPE                  129
#define IDI_ICON_SMALL                  130
#define IDB_MAINTB_DIS                  131
#define IDB_MAINTB_HOT                  132
#define PATTB_DELETE                    133
#define IDD_OPERBAR                     134
#define IDD_TYPERES                     140
#define IDD_RES                         141
#define IDD_OPERCLASSIF                 142
#define IDD_OPERCARD                    145
#define IDD_CLASSIFOPER                 148
#define IDD_OPERDOCCARAD                149
#define IDC_LISTSTB                     150
#define IDB_LOGON                       151
#define IDR_TBPOPUPMENU_DIC             153
#define IDR_HTML_SERV_PRINT             153
#define IDR_HTML_RPTFULLOPERSLIST       153
#define IDR_CHARTPOPUPMENU              155
#define IDB_PRINT                       156
#define IDD_PRICES                      161
#define IDR_HTML_RPTLOADOPERDAY         162
#define IDR_HTML_RPTLOADOPERWEEK        168
#define IDR_PRINT                       188
#define IDD_CHANGE_VISIT_AGR            195
#define IDD_PLAN_OUT                    198
#define IDD_DEP_DIALOG                  200
#define PATTB_CHANGE_LEFT               207
#define IDOK                            1085
#define IDCANCEL                        1086
#define IDC_LIST1                       1087
#define IDC_DEP_LIST                    1087
#define IDC_DATETIMEPICKER1             3000
#define IDC_CMB_OPER                    3001
#define IDC_CMB_OPER_DEPS               3001
#define IDC_EDITTYPERES                 3002
#define IDC_EDITRES                     3003
#define IDC_EDITOPERCLASSIF             3005
#define IDC_EDITPLACE_CARD              3006
#define IDC_EDITPATIENT_CARD            3007
#define IDC_DATETIMEBGN_CARD            3010
#define IDC_DATETIMEEND_CARD            3011
#define IDC_OPERLIST_CARD               3012
#define IDC_MAINDOCLIST_CARD            3013
#define IDC_ANESTLIST_CARD              3015
#define IDC_OPERINS_CARD                3016
#define IDC_OPERDEL_CARD                3017
#define IDC_MAINDOCINS_CARD             3018
#define IDC_MAINDOCDEL_CARD             3019
#define IDC_TYP_PLACE                   3019
#define IDC_ANESTDOCINS_CARD            3020
#define IDC_ANESTDOCDEL_CARD            3021
#define IDC_CLASSIFOPER                 3022
#define IDC_DATETIMEBGN_DOCCARD         3023
#define IDC_DATETIMEEND_DOCCARD         3024
#define IDC_EDITPLACE_DOCCARD           3025
#define IDC_EDITPATIENT_DOCCARD         3026
#define IDC_OPERINS_DOCCARD             3027
#define IDC_OPERDEL_DOCCARD             3028
#define IDC_OPERLIST_DOCCARD            3029
#define IDC_RBMAINDOC                   3030
#define IDC_RBANESTDOC                  3031
#define IDC_APPLYDATA                   3035
#define IDC_PROTOCOL_TYPE               3041
#define IDC_BCATEG2                     3054
#define IDC_ANKETA                      3061
#define IDC_PROF3                       3061
#define IDC_PROF2LABEL2                 3074
#define IDC_DIAGNOS                     3075
#define IDB_ADDTBDIS                    3139
#define PATTB_CHANGE_PROFILE            3215
#define ID_MI_BED_GANT                  3217
#define PATTB_MOVE_TO_ADDITIONAL        3220
#define PATTB_DEL_CHANGE_DOC            3222
#define ID_CM_MOTHER_CARE               32771
#define ID_RP_OPERDAYLOAD               32772
#define ID_RP_OPERWEEKLOAD              32773
#define ID_RP_OPERDONE                  32774
#define ID_RP_OPERDONE_CAH              32775
#define ID_CM_OPERCLASSIF               32777
#define ID_CM_HOSPRES                   32778
#define ID_MI_PATIENTSERVICE            32785
#define ID_CM_HISTORY                   32798
#define ID_CM_ASSIGN                    32802
#define IDM_DIET_SVOD                   32804
#define ID_MENUITEM32808                32808
#define ID_CM_LISTS                     32809
#define ID_CM_RESERVATION               32810
#define ID_CM_HOSPITALISATION           32811
#define ID_MENUITEM32813                32813
#define ID_CM_OPERDAY_TBL               63205
#define ID_CM_OPERDAY_CHART             63206
#define OPERTB_INSERT                   63207
#define OPERTB_DELETE                   63208
#define OPERTB_EDIT                     63209
#define PATTB_MOVE_TO_RESERV            63233
#define PATTB_PAYTYPE                   63235
#define PATTB_PRINT_VEDOM_DEP           63248
#define PATTB_CHANGE_DEF_PAT            63249
#define PATTB_CHANGE_VISIT_AGR          63250
#define PATTB_PLAN_MOVE_OUT             63253
#define PATTB_CHANGES                   63254
#define PATTB_OUTS                      63255
#define PATTB_MOVES                     63256
#define PATTB_CANCEL_PLAN_MOVE_OUT      63257

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
