//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ArmMoving.rc
//
#define IDCANCEL2                       4
#define IDR_MAINFRAME                   128
#define IDR_ARMOPETYPE                  129
#define IDI_ICON_SMALL                  130
#define IDB_MAINTB                      130
#define PATTB_DEL_CHANGE_BED            130
#define IDB_MAINTB_DIS                  131
#define PATTB_DEL_MOVE_FROM             131
#define IDB_MAINTB_HOT                  132
#define PATTB_DEL_LEFT                  132
#define PATTB_DELETE                    133
#define IDD_OPERBAR                     134
#define IDD_TYPERES                     140
#define IDD_RES                         141
#define IDD_OPERCLASSIF                 142
#define IDD_OPERCARD                    145
#define IDB_SBTINS                      146
#define IDD_CLASSIFOPER                 148
#define IDD_OPERDOCCARAD                149
#define IDC_LISTSTB                     150
#define IDB_LOGON                       151
#define IDD_RPTFULLOPERSLIST            152
#define IDR_TBPOPUPMENU_DIC             153
#define IDR_HTML_SERV_PRINT             153
#define IDR_HTML_RPTFULLOPERSLIST       153
#define IDR_TBPOPUPMENU_REP             154
#define IDR_CHARTPOPUPMENU              155
#define IDB_PRINT                       156
#define IDD_RPTLOADOPERDAY              159
#define IDD_RPTLOADOPERWEEK             160
#define IDD_PRICES                      161
#define IDR_HTML_RPTLOADOPERDAY         162
#define IDD_OUT                         163
#define IDB_EXCEL                       164
#define IDB_HTML                        167
#define IDR_HTML_RPTLOADOPERWEEK        168
#define IDB_DEPTB                       174
#define IDB_PATTB                       175
#define IDB_DATETB                      176
#define IDB_DATETB_DIS                  177
#define IDR_MENU1                       178
#define IDD_FIRST_DEP                   179
#define IDB_BITMAP1                     180
#define IDD_CHANGE_BED                  181
#define IDD_CHANGE_DEP                  182
#define IDD_LIST_TBPNL                  184
#define IDB_COLORS                      187
#define IDR_PRINT                       188
#define IDD_BED_RESERV                  190
#define IDR_PATMENU                     191
#define IDD_DEPPATS_DLG                 193
#define IDB_POSTOVAYA                   194
#define IDD_CHANGE_VISIT_AGR            195
#define IDD_CUSTOM_SEARCH_DATA          196
#define IDB_PATTB_DIS                   197
#define IDD_PLAN_OUT                    198
#define IDM_SVOD                        205
#define IDM_SVOD_PAT                    206
#define PATTB_CHANGE_LEFT               207
#define IDD_CHANGE_DOC                  209
#define IDD_CHANGE_DEF_PAT              210
#define IDC_COL_DR                      331
#define IDC_START_ROW                   332
#define PATTB_MOVE_CHANGE_PO            333
#define PATTB_MOVE_ADD                  334
#define PATTB_MOVE_DELETE               335
#define PATTB_MOVE_PAYTYPE              336
#define PATTB_ALL_EVENT_CHANGE          337
#define PATTB_ALL_EVENT_CANCEL          338
#define IDC_DATETIMEPICKER1             3000
#define IDC_CMB_OPER                    3001
#define IDC_CMB_OPER_DEPS               3001
#define IDC_BGNDATE                     3001
#define IDC_EDITTYPERES                 3002
#define IDC_EDITRES                     3003
#define IDC_EDITOPERCLASSIF             3005
#define IDC_EDITPLACE_CARD              3006
#define IDC_EDITPATIENT_CARD            3007
#define IDC_DATETIMEBGN_CARD            3010
#define IDC_DATETIMEEND_CARD            3011
#define IDC_OPERLIST_CARD               3012
#define IDC_MAINDOCLIST_CARD            3013
#define IDC_ANESTLIST_CARD              3015
#define IDC_OPERINS_CARD                3016
#define IDC_OPERDEL_CARD                3017
#define IDC_MAINDOCINS_CARD             3018
#define IDC_MAINDOCDEL_CARD             3019
#define IDC_TYP_PLACE                   3019
#define IDC_ANESTDOCINS_CARD            3020
#define IDC_ANESTDOCDEL_CARD            3021
#define IDC_PRINT_TO_EXCEL              3021
#define IDC_CLASSIFOPER                 3022
#define IDC_DATETIMEBGN_DOCCARD         3023
#define IDC_DATETIMEEND_DOCCARD         3024
#define IDC_EDITPLACE_DOCCARD           3025
#define IDC_EDITPATIENT_DOCCARD         3026
#define IDC_OPERINS_DOCCARD             3027
#define IDC_OPERDEL_DOCCARD             3028
#define IDC_OPERLIST_DOCCARD            3029
#define IDC_RBMAINDOC                   3030
#define IDC_RBANESTDOC                  3031
#define IDC_APPLYDATA                   3035
#define IDC_ENDDATE                     3037
#define IDC_PRINT_TO_HTML               3038
#define IDC_ALLDEPS                     3041
#define IDC_PROTOCOL_TYPE               3041
#define IDC_SELECTDEP                   3042
#define IDC_PATDIAGBGN_CODE             3047
#define IDC_OUT_TYPE                    3048
#define IDC_OUT_AS_DEP                  3049
#define IDC_PROF                        3051
#define IDC_BCATEG                      3052
#define IDC_ADD_BED                     3053
#define IDC_PROF2                       3054
#define IDC_BCATEG2                     3054
#define IDC_RESERVE_BED                 3054
#define IDC_REFRESH                     3055
#define IDC_PATDIAGBGN                  3055
#define IDC_APPLY_FOR_ALL               3056
#define IDC_FIO                         3059
#define IDC_ANKETA                      3061
#define IDC_STATIC_ASDEP                3061
#define IDC_PROF3                       3061
#define IDC_DEP_SELECT                  3062
#define IDC_BED_SELECT                  3063
#define IDC_PATIENT                     3064
#define IDC_BCOMPLEX                    3065
#define IDC_CHECK_ANOTHER               3070
#define IDC_PROF2LABEL                  3073
#define IDC_PROF2LABEL2                 3074
#define IDC_DIAGNOS                     3075
#define IDC_AGR_STATIC                  3075
#define IDC_BROWSE                      3077
#define IDC_FILENAME                    3078
#define IDC_COL_FIO                     3079
#define IDC_CREATEDATE                  3083
#define IDC_UPDATEDATE                  3084
#define PATTB_MOVE_OUT                  3119
#define PATTB_REFRESH                   3133
#define IDB_ADDTBDIS                    3139
#define IDD_FIRST_DEP_RESERV            3208
#define PATTB_CHANGE_PROFILE            3215
#define ID_MI_BED_GANT                  3217
#define IDD_SELECTDATE_DLG              3219
#define PATTB_MOVE_TO_ADDITIONAL        3220
#define PATTB_CHANGE_DOC                3221
#define PATTB_DEL_CHANGE_DOC            3222
#define IDC_CB_PROF_DEP                 3223
#define IDB_SBTDEL                      3475
#define ID_CM_MOTHER_CARE               32771
#define ID_RP_OPERDAYLOAD               32772
#define ID_RP_OPERWEEKLOAD              32773
#define ID_RP_OPERDONE                  32774
#define ID_RP_OPERDONE_CAH              32775
#define ID_CM_OPERCLASSIF               32777
#define ID_CM_HOSPRES                   32778
#define ID_CM_RESHOSP                   32779
#define ID_MI_PATIENTSERVICE            32785
#define ID_CHARTINSERT                  32786
#define ID_CHARTUPDATE                  32787
#define ID_CHARTDELETE                  32788
#define ID_CM_HISTORY                   32798
#define ID_CM_MOVE                      32798
#define ID_CM_SUMMARY                   32799
#define ID_CM_BED_FUND                  32800
#define IDM_DEP_LIST                    32801
#define ID_CM_ASSIGN                    32802
#define PATTB_RESTB_CHANGE              32802
#define PATTB_RESTB_TAKEOFF             32803
#define IDM_DIET_SVOD                   32804
#define PATTB_RESTB_CANCEL              32804
#define IDM_PAT_ON_DEPS                 32805
#define ID_MENUITEM32808                32808
#define ID_CM_LISTS                     32809
#define ID_CM_RESERVATION               32810
#define ID_CM_HOSPITALISATION           32811
#define ID_MENUITEM32813                32813
#define ID_MI_PROPERTIES                32814
#define IDM_PAT_SEARCH_BY_SMP           32815
#define ID_COLOR_INFO                   32820
#define ID_CM_PATSEARCH                 63204
#define ID_CM_OPERDAY_TBL               63205
#define ID_CM_OPERDAY_CHART             63206
#define OPERTB_INSERT                   63207
#define OPERTB_DELETE                   63208
#define OPERTB_EDIT                     63209
#define IDC_TYPERESGRID                 63211
#define IDC_RESGRID                     63212
#define TYPERESTB_INSERT                63213
#define TYPERESTB_DELETE                63214
#define TYPERESTB_EDIT                  63215
#define RESTB_INSERT                    63216
#define RESTB_DELETE                    63217
#define RESTB_EDIT                      63218
#define OPERCLASSIFTB_INSERT            63219
#define OPERCLASSIFTB_DELETE            63220
#define OPERCLASSIFTB_EDIT              63221
#define IDC_OPERCLASSIFGRID             63222
#define OPERTABLETB_INSERT              63223
#define OPERTABLETB_DELETE              63224
#define OPERTABLETB_EDIT                63225
#define PATTB_MOVE_FROM                 63226
#define ID_CM_REPORTS                   63227
#define ID_CHART_INS                    63228
#define ID_EXCEL                        63229
#define ID_PRINT                        63230
#define ID_MI_SETDATE                   63231
#define PATTB_MOVE_TO                   63232
#define PATTB_MOVE_TO_RESERV            63233
#define PATTB_CHANGE_BED                63234
#define PATTB_PAYTYPE                   63235
#define ID_SVODHIST_ADD                 63245
#define PATTB_PRINT_VEDOM               63247
#define PATTB_PRINT_VEDOM_DEP           63248
#define PATTB_CHANGE_DEF_PAT            63249
#define PATTB_CHANGE_VISIT_AGR          63250
#define PATTB_PRINT_VEDOM_LAB           63251
#define PATTB_PLAN_MOVE_OUT             63253
#define PATTB_CHANGES                   63254
#define PATTB_OUTS                      63255
#define PATTB_MOVES                     63256
#define PATTB_CANCEL_PLAN_MOVE_OUT      63257
#define PATTB_MOVE_TO_PREV              63258

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
